POST http://localhost:8000/input-product-v1 HTTP/1.1
Content-Type: application/json

{
    "id": "P0002",
    "product_name": "Simpati 22GB",
    "price": 50000,
    "quantity": 10,
    "category": "kartu perdana"
}

#####
GET http://localhost:8000/product-v1 HTTP/1.1


####
PUT http://localhost:8000/update-product-v1 HTTP/1.1
Content-Type: application/json

{
    "productId": "P0001",
    "fildName": "category",
    "value": "voucher"
}
